let data = [
    {
        "id": 1,
        "imagen":"https://lapizzerianewgroup.netlify.app/img/productos/1/thumb0000.jpg",
        "titulo": "Especial I",
        "ingredientes": "Salsa, muzza, rúcula, jamón crudo, tomates deshidratados, parmesano",
        "precio": "$3500",
        "boton":"PEDIR",
    },
    {
        "id": 2,
        "imagen":"https://lapizzerianewgroup.netlify.app/img/productos/2/thumb0000.jpg",
        "titulo": "Veggie",
        "ingredientes": "Salsa, muzza, zucchinis y berenjenas asados, tomates cherrys confitados, olivas negras, hojas de albahaca",
        "precio": "$3200",
        "boton":"PEDIR",
    },
    {
        "id": 3,
        "imagen":"https://lapizzerianewgroup.netlify.app/img/productos/3/thumb0000.jpg",
        "titulo": "Especial II",
        "ingredientes": "Muzzarella, cebolla cortada en pluma,tomates cherrys confitados, olivas negras",
        "precio": "$3750",
        "boton":"PEDIR",
    },
    {
        "id": 4,
        "imagen":"https://lapizzerianewgroup.netlify.app/img/productos/6/thumb0000.jpg",
        "titulo": "Fugazzetta Rellena",
        "ingredientes": "Muzzarella, cebolla cortada en pluma, rellena con más muzza, olivas negras",
        "precio": "$4000",
        "boton":"PEDIR",
    },
    {
        "id": 5,
        "imagen":"https://lapizzerianewgroup.netlify.app/img/productos/5/thumb0000.jpg",
        "titulo": "Dantezca",
        "ingredientes": "Salsa, muzza, panceta feteada, jalapeños verdes en rodajas, salsa de jalapeño rojo, cebolla morada, provolone rallado y hojas de albahaca",
        "precio": "$4000",
        "boton":"PEDIR",
    },
    {
        "id": 6,
        "imagen":"https://lapizzerianewgroup.netlify.app/img/productos/6/thumb0000.jpg",
        "titulo": "Fugazzetta Jamón",
        "ingredientes": "Muzzarella, cebolla cortada en pluma, Jamón especial, olivas negras",
        "precio": "$4000",
        "boton":"PEDIR",
    },
    {
        "id": 7,
        "imagen":"https://lapizzerianewgroup.netlify.app/img/productos/7/thumb0000.jpg",
        "titulo": "Fugazzetta Pepperoni",
        "ingredientes": "Muzzarella, cebolla cortada en pluma, Pepperoni especial, olivas negras",
        "precio": "$3900",
        "boton":"PEDIR",
    },
    {
        "id": 8,
        "imagen":"https://lapizzerianewgroup.netlify.app/img/productos/4/thumb0000.jpg",
        "titulo": "German",
        "ingredientes": "Salsa, muzza, cebolla caramelizada, salchicha parrillera y mostaza",
        "precio": "$4000",
        "boton":"PEDIR",
    },
    {
        "id": 9,
        "imagen":"https://lapizzerianewgroup.netlify.app/img/productos/2/thumb0000.jpg",
        "titulo": "Veggie Rellena",
        "ingredientes": "Masa rellena con la mejor Muzza, salsa, más muzza, zucchinis y berenjenas asados, tomates cherrys confitados, olivas negras, hojas de albahaca",
        "precio": "$4100",
        "boton":"PEDIR",
    }
    
]